language: python

sudo: required

services:
  - docker

before_install:
 - docker pull mysql:5.7.14
 - mkdir db
 - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
 - sleep 15  #wait for container to start
 - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.14 mysql -uroot -p'$3cureUS' -h db -e "CREATE USER 'www'@'%' IDENTIFIED BY '\$3cureUS'; CREATE DATABASE cs4501 CHARACTER SET utf8; GRANT ALL PRIVILEGES ON *.* TO 'www'@'%';"
 
before_script:
 - docker-compose up -d
 - docker start mysql

script:
 - docker exec -it models bash -c "cd models && python manage.py test"

after_script:
 - docker-compose down
 - docker rm 'docker ps -a -q'
 - rm -rf db
